peex:
  outputs:
    dev:
      dbname: peex
      host: peex.ck12mwo4g6gp.us-east-1.rds.amazonaws.com
      pass: Legionisci1!
      port: 5432
      schema: warehouse
      threads: 1
      type: postgres
      user: postgres
  target: dev
