
version: 2

models:
  - name: stg_agency
    description: "Agencies model"
    columns:
      - name: agency_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: stg_astronaut
    description: "A starter dbt model"
    columns:
      - name: astronaut_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
